language: python

python:
  - 3.6.5

services:
  - postgresql

addons:
  apt:
    packages:
    - ldap-utils
    - slapd

install:
  - pip install -r requirements.pip

before_script:
  - cp django_ldap_user_registration/local_settings.py.default django_ldap_user_registration/local_settings.py
  - export DJ_DEBUG=False
  - export DATABASE_URL=postgres://postgres@localhost/travisdb
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python manage.py migrate

deploy:
  provider: heroku
  api_key:
    secure: WWpdJuDt1xz/+ZVJVgD1hlVMmnyUf95+W+8aTrrDYWbirnUOFXIj5gJ9F2RxPziBoLSO8toCRSPG95UWBUgF59RbUX6mbEPwncJFgy/+LwV7khrxqcyjaL5HKVEmzxVtulTXuF+Ft83VD9TMMBVCJiqLXtDhoxiIdtUOtBu7a8OrI7vPcteZmMROYCbdhOZmUYoYWonJdiabjPefThlFLDeWWa05XpiXmGWKgCJ9lbDbJ83+vVLmWqTcAER7Sgd3ZgqSvedpVPzLEUge9+KhpKZXWcPE8Go7SEMJ/gytsG4Bg8/OQvThmrKvPf9iLPzXiEhg8OkkLKmtgSElIO2/9GA92nc/iApqoMoGM6WNqAOWBV+iQyC9lVP12rrp+LFbDG0tDJmjQ2EduZoLJLB7UxTTU2jcK++HHjVV8fUI7nwlMXju3CBbmN7SZCMlFALmshTeCEVpEGLTKVesa/AcPtXHGFAImjJcNc5pJ8TCpPlnwY4eFbe+SNpg17NCnl4iCEBAj6UXVd16aSYH33UvXfuZoC0UeyJWKqWxi+DDu94TabnvnUZqMWnoRAfNtQO2kankziLR/lhbKUC4qji6N2OwFjak8Mc3xKMaGm+tF25OyLroCSTaAMjKNo20rs1tB0VvmpXMjGeiJw0kclqnd+3HDldoExmc9mwrX4gQSpc=
  app: django-ldap-user-registration
  on:
    repo: KENET-KE/django-ldap-user-registration
  run:
   - "export DJ_DEBUG=False"
   - "export DATABASE_URL=postgres://postgres@localhost/travisdb"
   - "python KENET-KE/django-ldap-user-registration/manage.py migrate"

script: "echo 1"

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://readthedocs.org/build/django-ldap-user-registration
    on_start: never
    on_cancel: never
    on_error: never
    on_failure: never
on_success: always